### ISSUE TITLE
Use semantic HTML for clean theme

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#29]
https://developer.mozilla.org/en-US/docs/Glossary/Semantics

**Comment by rickansen** [comment]
Good evening, would love to work on this :)) Can I have this assigned to me? Thank you.

**Comment by jofftiquez** [comment]
> Good evening, would love to work on this :)) Can I have this assigned to me? Thank you.

Go ahead @rickansen <3 thank you!
