### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#3]
Add screenshots of each template to the main README.md

The links are available in the docs, e.g - https://ossphilippines.github.io/freefolio/hacker/

**Comment by yashfalke77** [comment]
@jofftique can I do this, it will be my first open source contribution :)

**Comment by jofftiquez** [comment]
> @jofftique can I do this, it will be my first open source contribution :)

Hello somebody already sent a PR, there's still a comment tho, you can improve the existing PR. Thanks.
