### ISSUE TITLE
Use semantic HTML for plain theme

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#33]
https://developer.mozilla.org/en-US/docs/Glossary/Semantics

**Comment by getmeapencil** [comment]
I would like to contribute.

**Comment by Deevyne99** [comment]
i have resolved the issue please can you add me as a contributor so i can push my branch

**Comment by jofftiquez** [comment]
> i have resolved the issue please can you add me as a contributor so i can push my branch

Hello, thank you for that. You are not allowed to push directly to the project, but you can create a pull request so we can review your work. 

Here's a guide on how to do it https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by jofftiquez** [comment]
> Issue has been resolved from this [PR](https://github.com/OSSPhilippines/freefolio/pull/76)
> 
> Permission to close this.

You can close issues that are verified to have been resolved already, thank you
