### ISSUE TITLE
Add additional template

### ISSUE THREAD

**Issue by artdev-hash** [OSSPhilippines/freefolio#37]
**Is your feature request related to a problem? Please describe.**
It's not a problem, just a proposal / a suggestion.

**Describe the solution you'd like**
A Contribution

**Describe alternatives you've considered**
Maybe submit other templates but for approval

**Additional context**
that would be all..thank you..

**Comment by HassanShanJava** [comment]
Hi have a basic template I would like to contribute, could you assign it to me? or could I just fork it and contribute anyway?
?

**Comment by HassanShanJava** [comment]
I just sent the pull request, it has a detail overview of the work I have done, do check and let me know if there's an issue
