### ISSUE TITLE
Add link to OSSPH website

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#53]
In the home page there's an OSSPH logo in the toolbar. Add a link to that logo (https://ossph.org)

![image](https://user-images.githubusercontent.com/8638243/210919518-01193b3a-edae-4a9a-a477-5436784c4c87.png)

**Comment by AbbeyIT** [comment]
Hello, I would like to work on this issue.

**Comment by jofftiquez** [comment]
> Hello, I would like to work on this issue. Can you assign it to me?

Go ahead, thank you!

**Comment by mpotane** [comment]
Fixed #54
