### ISSUE TITLE
Update 404 page

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/freefolio#56]
The current page looks like this:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/8638243/213089294-8f66e565-435a-4165-b10b-c7782aefffd9.png">

Feel free to design your own, just make sure it has a similar feel with what's in the `index.html`

**Comment by Taiga-Tiny** [comment]
![127 0 0 1_5500_index html (8)](https://user-images.githubusercontent.com/58163091/213375642-8a4fc1d4-651e-46a6-b906-2af9f398b5cb.png)

is it okay guru?

**Comment by jofftiquez** [comment]
This should be fine for now @Taiga-Tiny thanks <3 My only comment would be you should match the colors with what we have in the index page https://freefolio.web.app/

**Comment by Taiga-Tiny** [comment]
my bad

**Comment by jofftiquez** [comment]
> my bad

No, it's okay don't be sorry. Thanks :D

**Comment by jemstone** [comment]
The PR for this has been merged. Closing this issue now. Thank you
