### ISSUE TITLE
Tailwind cdn is complaining that it shouldn't be run on production.

### ISSUE THREAD

**Issue by mpotane** [OSSPhilippines/freefolio#62]
![image](https://user-images.githubusercontent.com/65337802/213439117-f065208d-26fe-4676-858f-76b759648b59.png)

**Comment by jofftiquez** [comment]
Suggested work for this:

- Follow the tailwind installation and build guide

**Comment by mpotane** [comment]
> Suggested work for this:
> 
> * Follow the tailwind installation and build guide

I assume we use Yarn as a package manager? @jofftiquez 
I will submit a draft pr this hacktoberfest 😋
